# -*- coding: utf-8 -*-
"""从 primary.html 的言行实录账本生成可交互时间轴，注入账本列表之前。

用法：python tools/build-ledger-timeline.py
（站点根目录执行；账本条目变动后重跑一次即可刷新时间轴。）

产物：primary.html 中 PS-TIMELINE:BEGIN/END 标记之间的时间轴块（可重复执行，幂等重建）。
纯 CSS/SVG 定位实现，无任何图表库；节点为真实 <a> 锚点链接，hover/focus 显示摘要。
"""
import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

p = 'primary.html'
s = io.open(p, encoding='utf-8').read()

blocks = re.findall(r'(<li class="ps-row[^"]*" id="(e\d[\d-]*)">.*?</li>)', s, re.S)
assert len(blocks) >= 44, len(blocks)
rows = []
for full, eid in blocks:
    date = re.search(r'Permalink">([^<]+)</a>', full)
    src = re.search(r'<span class="ps-src">([^<]+)</span>', full)
    quote = re.search(r'<blockquote class="ps-quote">(.*?)</blockquote>', full, re.S)
    assert date and src, eid
    rows.append((eid, date.group(1), src.group(1), quote.group(1) if quote else None))

def date_key(d):
    m = re.match(r'(\d{4})\.?(\d{1,2})?\.?(\d{1,2})?', d)
    y = int(m.group(1))
    mo = int(m.group(2) or 1)
    return y + (mo - 0.5) / 12.0

Y0, Y1 = 2002, 2027  # 线性映射区间
def pct(d):
    return (date_key(d) - Y0) / (Y1 - Y0) * 100.0

dots = []
for eid, date, src, quote in rows:
    tip = re.sub(r'\s+', ' ', src)
    if len(tip) > 52:
        tip = tip[:52] + '…'
    q = re.sub(r'<[^>]+>', '', quote or '')
    q = re.sub(r'\s+', ' ', q).strip()[:64]
    qs = f'<br><i>“{q}…”</i>' if q else ''
    dots.append(f'<a class="pt-dot" href="#{eid}" style="left:{pct(date):.2f}%"><span class="pt-tip"><b>{date}</b> {tip}{qs}</span></a>')

years = list(range(2002, 2028, 4))
ticks = ''.join(f'<span class="pt-year" style="left:{(y - Y0) / (Y1 - Y0) * 100:.2f}%">{y}</span>' for y in years)

block = ('<!-- PS-TIMELINE:BEGIN (generated by tools/build-ledger-timeline.py) -->\n'
         '  <h4 class="ps-label reveal pt-heading" style="margin-top:18px">时间轴 · 悬停看摘要，点击跳到该条</h4>\n'
         '  <div class="ps-timeline-wrap">\n'
         '    <div class="ps-timeline" id="ps-timeline" role="navigation" aria-label="言行实录时间轴，' + str(len(dots)) + ' 个节点，点击跳转对应条目">\n'
         f'      <div class="pt-axis"></div>{ticks}\n'
         '      ' + '\n      '.join(dots) + '\n'
         '    </div>\n'
         '  </div>\n'
         '<!-- PS-TIMELINE:END -->')

BEGIN, END = '<!-- PS-TIMELINE:BEGIN', '<!-- PS-TIMELINE:END -->'
if BEGIN in s:
    s = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), block, s, flags=re.S)
else:
    anchor = '<ol class="ps-ledger">'
    assert s.count(anchor) == 1
    s = s.replace(anchor, block + '\n' + anchor, 1)

io.open(p, 'w', encoding='utf-8', newline='\n').write(s)
print(f'primary.html: 时间轴重建，{len(dots)} 个节点')
